FROM python:3.11
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY generate_dataset.py .
RUN python generate_dataset.py

COPY train_model.py .
RUN python train_model.py --data spam_dataset.csv --out model.joblib

COPY app.py .
EXPOSE 8080
CMD ["uvicorn", "app:app","--host", "0.0.0.0", "--port", "8080"]
